### ISSUE TITLE
SFH

### ISSUE THREAD

**Issue by OM3GA6400** [FlafyDev/auto-nong#1]
can you add sfh nong downloading?

**Comment by FlafyDev** [comment]
Downloading songs from sfh works. It downloads from either youtube or @RoootTheFox's mirror.
I won't make this mod download directly from sfh as they don't want modders to do that.

**Comment by RoootTheFox** [comment]
adding on to this real quick - ill go ahead and implement periodic automatic SFH syncing ~ atm it needs to be done manually which isn't ideal
luckily the way i implemented initial sync should allow me to easily reuse it for periodic syncing
