### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by ChromanicAI** [FlafyDev/auto-nong#23]
I'm running GD on Arch and have yt-dlp installed from official repos. Can I use the system python package of yt-dlp or i need to use the windows equivalent in .exe format?

**Comment by FlafyDev** [comment]
I'm pretty sure you have to use yt-dlp's windows exe file if you are running gd through wine. Linux executable wouldn't work

**Comment by ChromanicAI** [comment]
Ok, thanks for the answer
