### ISSUE TITLE
Bug: Setting nong for a level with 2 nongs crashes the game

### ISSUE THREAD

**Issue by simpansoftware** [FlafyDev/auto-nong#3]
When using this mod and downloading nongs from a level with 2 nongs the game crashes. 

Log: [2024-04-07_09-54-50.log](https://github.com/FlafyDev/auto-nong/files/14896279/2024-04-07_09-54-50.log)

**Comment by FlafyDev** [comment]
Do you have a level id I can reproduce this crash with?

**Comment by simpansoftware** [comment]
> Do you have a level id I can reproduce this crash with?

Golden hope

**Comment by simpansoftware** [comment]
When setting the second nong the game crashed

**Comment by FlafyDev** [comment]
I think that happens when you set a song that is Unknown in Jukebox before v2.7.0.

I just checked and everything works fine in Jukebox v2.7.0 + Auto Nong v0.0.3. Can you try those?

also you don't have to set the second song in golden hope

**Comment by simpansoftware** [comment]
Works now
