### ISSUE TITLE
feat: allow for non gzipped json indexes

### ISSUE THREAD

**Issue by eye-wave** [FlafyDev/auto-nong#4]
would be really handy to not have to gzip my list every time i add something new

**Comment by FlafyDev** [comment]
Why do you need it?
It's usually better to compress and decompress so downloading the JSON will take a lot less bytes.
And it shouldn't be inconvenient: You add JSON to `official.json` in the main branch in https://github.com/FlafyDev/auto-nong-indexes and it automatically generates the gzipped json in the dist branch.

**Comment by FlafyDev** [comment]
makes sense. I'll add it when I have the chance
