### ISSUE TITLE
The link not going ininto GD

### ISSUE THREAD

**Issue by HXDdarkwolf** [FlafyDev/auto-nong#45]
Hi, So I want to add "https://www.youtube.com/watch?v=x8VYWazR5mE&rco=1&ab_channel=Ayase%2FYOASOBI" you GD for my use on a layout I created, and for some reason the link just wont work. Ive tried to replace the link multiple times and it still wont work.

![Screenshot 2024-10-03 174138](https://github.com/user-attachments/assets/421179b8-3026-4c9a-bf15-1ddbbe1e935c) 

![Screenshot 2024-10-03 174222656565656](https://github.com/user-attachments/assets/70b02c79-0810-4c2d-ba74-29b976ecf9a1)

![Screenshot 2024-10-03 1742454536534665435346](https://github.com/user-attachments/assets/ccc85da9-288e-4670-94ba-fc9e464c819b)

There in chronological order so these screen shots are how its going on in the game, I really don't know whats going on.

**Comment by FlafyDev** [comment]
Works as expected. `https://www.youtube.com/watch?v=x8VYWazR5mE&rco=1` turns into `x8VYWazR5mE`.

The song doesn't work because its age restricted and requires youtube login. So it can't be downloaded.
