### ISSUE TITLE
Doesn't work with new version of jukebox

### ISSUE THREAD

**Issue by OM3GA6400** [FlafyDev/auto-nong#5]
![image](https://github.com/FlafyDev/auto-nong/assets/98067930/afadf95e-fae7-4a9f-92d9-0abe68e8e052)

**Comment by OM3GA6400** [comment]
just updated jukebox and got this error

**Comment by FlafyDev** [comment]
that's weird.. I just updated jukebox to v2.7.0 as well and redownloaded v0.0.2 from the index and I don't get this error..

**Comment by OM3GA6400** [comment]
ill remove all my mods other than jukebox and auto nong and try

**Comment by FlafyDev** [comment]
Ah. auto nong works but when downloading any song it crashes when trying to set it.

**Comment by OM3GA6400** [comment]
just removed all other mods and the error still occurs 
![image](https://github.com/FlafyDev/auto-nong/assets/98067930/aca6cdcd-9992-4234-b079-28d29bb6e15d)

**Comment by FlafyDev** [comment]
can you try this? https://file.io/llPj8ZVgiNea
@OM3GA6400 

I updated to the new jukebox version

**Comment by OM3GA6400** [comment]
bet
