### ISSUE TITLE
Songs won't download

### ISSUE THREAD

**Issue by BAGAS703** [FlafyDev/auto-nong#51]
https://github.com/user-attachments/assets/8c3e037b-db70-484a-853b-589e7290675f

**Comment by TTVMic8** [comment]
easy fix: i have no fucking idea whats going on it happened to me too

**Comment by TTVMic8** [comment]
but try to remove nongs for that id on jukebox maybe that will work
if all else fails just use jukebox and yt2mp3 until they respond (some yt2mp3 sites are scams or infested with ads so heres the link: https://ezmp3.cc/v1)

**Comment by FlafyDev** [comment]
The mod is deprecated. Use jukebox instead
